# Generated by Django 2.2 on 2021-02-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight_School_Coffee_app', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='order_size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
