# Generated by Django 2.2 on 2021-02-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight_School_Coffee_app', '0003_auto_20210209_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='order_size',
            field=models.IntegerField(),
        ),
    ]
