# Generated by Django 2.2 on 2021-02-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight_School_Coffee_app', '0004_auto_20210217_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffees',
            name='image',
        ),
        migrations.AddField(
            model_name='coffees',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
